function ardddt = ardddt_idt(i,d,t)
% Return the fourth mixed derivative of the residual normalized Helmholtz function with
% respect to delta and tau at a specified value of delta (d), and tau (t).

global FR_Npoly FR_Nexp FR_Ngaus FR_Nnonan
global FR_N FR_d FR_t FR_c
global FR_eta FR_beta FR_gamma FR_epsilon
global FR_a FR_b FR_NAbeta FR_A FR_B FR_C FR_D

% Build up the residual by the types of terms.
ardddt = 0;
k = 1;

% Start with the polynomial terms:
for(j=1:1:FR_Npoly(i))
    ardddt = ardddt + FR_t(k,i)*(FR_d(k,i)-2)*(FR_d(k,i)-1)*FR_d(k,i)*FR_N(k,i)*d^(FR_d(k,i)-3)*t^(FR_t(k,i)-1);
    k = k+1;
end

% Add the exponential terms:
for(j=1:1:FR_Nexp(i))
    ardddt = ardddt + ...
         (...
          (FR_d(k,i)-2)*(FR_d(k,i)-1)*FR_d(k,i)*d^(FR_d(k,i)-3) - ...
          2*(FR_c(k,i)-1)*FR_c(k,i)*FR_d(k,i)*d^(FR_c(k,i)+FR_d(k,i)-3) - ...
          3*(FR_d(k,i)-1)*FR_c(k,i)*FR_d(k,i)*d^(FR_c(k,i)+FR_d(k,i)-3) + ...
          3*FR_c(k,i)^2*FR_d(k,i)*d^(2*FR_c(k,i)+FR_d(k,i)-3) + ...
          3*(FR_c(k,i)-1)*FR_c(k,i)^2*d^(2*FR_c(k,i)+FR_d(k,i)-3) - ...    
          (FR_c(k,i)-2)*(FR_c(k,i)-1)*FR_c(k,i)*d^(FR_c(k,i)+FR_d(k,i)-3) - ...
          FR_d(k,i)*(FR_c(k,i)-1)*FR_c(k,i)*d^(FR_c(k,i)+FR_d(k,i)-3) - ... 
          FR_c(k,i)^3*d^(3*FR_c(k,i)+FR_d(k,i)-3)...
          )...
         *FR_t(k,i)*FR_N(k,i)*t^(FR_t(k,i)-1)*exp(-d^FR_c(k,i));
    k = k+1;
end

% Add the Gaussian terms:
for(j=1:1:FR_Ngaus(i))
    ardddt = ardddt + ...
        (...
          (FR_d(k,i)-2)*(FR_d(k,i)-1)*FR_d(k,i)*d^(FR_d(k,i)-3)...
        - 6*FR_eta(k,i)*(FR_d(k,i)-1)*FR_d(k,i)*(d-FR_epsilon(k,i))*d^(FR_d(k,i)-2)...
        - 6*FR_eta(k,i)*FR_d(k,i)*d^(FR_d(k,i)-1)...
        + 12*FR_eta(k,i)^2*(d-FR_epsilon(k,i))^2*FR_d(k,i)*d^(FR_d(k,i)-1)...
        + 12*FR_eta(k,i)^2*(d-FR_epsilon(k,i))*d^FR_d(k,i)...
        - 8*FR_eta(k,i)^3*(d-FR_epsilon(k,i))^3*d^FR_d(k,i)...
        )...
        *((FR_t(k,i)*t^(FR_t(k,i)-1)) + (-2*FR_beta(k,i)*(t-FR_gamma(k,i))*t^FR_t(k,i)))...
        *FR_N(k,i)*exp(-FR_eta(k,i)*(d-FR_epsilon(k,i))^2-FR_beta(k,i)*(t-FR_gamma(k,i))^2);
   k = k+1;
end

% Add the nonanalytic terms:
for(j=1:1:FR_Nnonan(i))
    Theta = (1-t) + FR_A(k,i)*((d-1)^2)^(1/(2*FR_NAbeta(k,i)));
    Delta = Theta^2 + FR_B(k,i)*((d-1)^2)^FR_a(k,i);
    Psi   = exp(-FR_C(k,i)*(d-1)^2-FR_D(k,i)*(t-1)^2);
    
    % Don't compute the non-analytic terms if sitting on critical.
    % Their limit as you approach critical is zero.
    if((Theta == 0)&&(Delta == 0)&&(Psi == 1))
        ardddt = ardddt + 0;
    else
        dTheta  = (d-1)*(1/(FR_NAbeta(k,i)))*FR_A(k,i)*((d-1)^2)^(1/(2*FR_NAbeta(k,i))-1);
        dDelta  = 2*Theta*dTheta + 2*(d-1)*FR_a(k,i)*FR_B(k,i)*((d-1)^2)^(FR_a(k,i)-1);
        dDeltab = FR_b(k,i)*Delta^(FR_b(k,i)-1)*dDelta;
        dPsi    = -2*FR_C(k,i)*(d-1)*Psi;

        d2Theta  = FR_NAbeta(k,i)^(-1)*FR_A(k,i)*((d-1)^2)^(1/(2*FR_NAbeta(k,i))-1)...
            + 2*(1/(2*FR_NAbeta(k,i))-1)*(d-1)^2*FR_NAbeta(k,i)^(-1)*FR_A(k,i)*((d-1)^2)^(1/(2*FR_NAbeta(k,i))-2);
        d2Delta  = 2*dTheta^2 + 2*Theta*d2Theta...
            + 2*FR_a(k,i)*FR_B(k,i)*((d-1)^2)^(FR_a(k,i)-1)...
            + 4*(FR_a(k,i)-1)*(d-1)^2*FR_a(k,i)*FR_B(k,i)*((d-1)^2)^(FR_a(k,i)-2);
        d2Deltab = FR_b(k,i)*(Delta^(FR_b(k,i)-1)*d2Delta + (FR_b(k,i)-1)*Delta^(FR_b(k,i)-2)*dDelta^2);
        d2Psi    = (2*FR_C(k,i)*(d-1)^2 - 1)*2*FR_C(k,i)*Psi;

        d3Theta  = 2*(d-1)*(1/(2*FR_NAbeta(k,i))-1)*FR_NAbeta(k,i)^(-1)*FR_A(k,i)*((d-1)^2)^(1/(2*FR_NAbeta(k,i))-2)...
            + 4*(1/(2*FR_NAbeta(k,i))-1)*(d-1)*FR_NAbeta(k,i)^(-1)*FR_A(k,i)*((d-1)^2)^(1/(2*FR_NAbeta(k,i))-2)...
            + 4*(1/(2*FR_NAbeta(k,i))-2)*(1/(2*FR_NAbeta(k,i))-1)*(d-1)^3*FR_NAbeta(k,i)^(-1)*FR_A(k,i)*((d-1)^2)^(1/(2*FR_NAbeta(k,i))-3);
        d3Delta  = 6*dTheta*d2Theta + 2*Theta*d3Theta...
            + 12*(d-1)*(FR_a(k,i)-1)*FR_a(k,i)*FR_B(k,i)*((d-1)^2)^(FR_a(k,i)-2)...
            + 8*(d-1)^3*(FR_a(k,i)-2)*(FR_a(k,i)-1)*FR_a(k,i)*FR_B(k,i)*((d-1)^2)^(FR_a(k,i)-3);
        d3Deltab = FR_b(k,i)*(Delta^(FR_b(k,i)-1)*d3Delta ...
            + (FR_b(k,i)-2)*(FR_b(k,i)-1)*Delta^(FR_b(k,i)-3)*dDelta^3 ...
            + 3*(FR_b(k,i)-1)*Delta^(FR_b(k,i)-2)*dDelta*d2Delta);
        d3Psi    = 4*FR_C(k,i)*(d-1)*2*FR_C(k,i)*Psi...
            + (2*FR_C(k,i)*(d-1)^2 - 1)*2*FR_C(k,i)*dPsi;

        tTheta    = -1;
        tDelta    = 2*Theta*tTheta;
        tPsi      = -2*FR_D(k,i)*(t-1)*exp(-FR_C(k,i)*(d-1)^2-FR_D(k,i)*(t-1)^2);
        tdDelta   = 2*tTheta*dTheta;
        tdDeltab  = (FR_b(k,i)-1)*FR_b(k,i)*Delta^(FR_b(k,i)-2)*tDelta*dDelta...
            + FR_b(k,i)*Delta^(FR_b(k,i)-1)*tdDelta;
        tdPsi     = -2*FR_C(k,i)*(d-1)*tPsi;
        td2Delta  = 2*tTheta*d2Theta;
        td2Deltab = FR_b(k,i)*(...
              (FR_b(k,i)-1)*Delta^(FR_b(k,i)-2)*tDelta*d2Delta...
            + Delta^(FR_b(k,i)-1)*td2Delta...
            + (FR_b(k,i)-2)*(FR_b(k,i)-1)*Delta^(FR_b(k,i)-3)*tDelta*dDelta^2 ...
            + 2*(FR_b(k,i)-1)*Delta^(FR_b(k,i)-2)*dDelta*tdDelta ...
            );
        td2Psi    = (2*FR_C(k,i)*(d-1)^2 - 1)*2*FR_C(k,i)*tPsi;
        
        td3Theta  = 0;
        td3Delta  = 2*tTheta*d3Theta + 2*Theta*td3Theta;
        td3Deltab = FR_b(k,i)*(...
            (FR_b(k,i)-1)*Delta^(FR_b(k,i)-2)*tDelta*d3Delta ...
            + Delta^(FR_b(k,i)-1)*td3Delta ...
            + (FR_b(k,i)-3)*(FR_b(k,i)-2)*(FR_b(k,i)-1)*Delta^(FR_b(k,i)-4)*tDelta*dDelta^3 ...
            + 3*(FR_b(k,i)-2)*(FR_b(k,i)-1)*Delta^(FR_b(k,i)-3)*dDelta^2*tdDelta ...
            + 3*(FR_b(k,i)-2)*(FR_b(k,i)-1)*Delta^(FR_b(k,i)-3)*tDelta*dDelta*d2Delta...
            + 3*(FR_b(k,i)-1)*Delta^(FR_b(k,i)-2)*tdDelta*d2Delta...
            + 3*(FR_b(k,i)-1)*Delta^(FR_b(k,i)-2)*dDelta*td2Delta...
            );
        td3Psi    = 4*FR_C(k,i)*(d-1)*2*FR_C(k,i)*tPsi...
            + (2*FR_C(k,i)*(d-1)^2 - 1)*2*FR_C(k,i)*tdPsi;

        ardddt = ardddt + FR_N(k,i)*(...
              (FR_b(k,i)-1)*FR_b(k,i)*Delta^(FR_b(k,i)-2)*tDelta*dDelta*(2*dPsi + d*d2Psi)...
            + FR_b(k,i)*Delta^(FR_b(k,i)-1)*tdDelta*(2*dPsi + d*d2Psi)...
            + FR_b(k,i)*Delta^(FR_b(k,i)-1)*dDelta*(2*tdPsi + d*td2Psi)...
            + FR_b(k,i)*Delta^(FR_b(k,i)-1)*tDelta*(3*d2Psi + d*d3Psi)...
            + Delta^FR_b(k,i)*(3*td2Psi + d*td3Psi)...
            + 3*td2Deltab*(Psi + d*dPsi)...
            + 3*d2Deltab*(tPsi + d*tdPsi)...
            + 2*tdDeltab*(2*dPsi + d*d2Psi)...
            + 2*dDeltab*(2*tdPsi + d*td2Psi)...
            + td3Deltab*d*Psi...
            + d3Deltab*d*tPsi...
            );
    end
    k = k+1;
end
